language: rust
rust:
  - 1.2.0

script:
  - cargo build --verbose
  - cargo test --verbose

notifications:
  email: false
  slack:
    rooms:
      - zatvobor:eLjCTZD2l85xl19hsSdxkMdN##oss-feed
    on_success: change
