extern crate sphlib;

mod sph_blake_test;
mod sph_bmw_test;
mod sph_cubehash_test;
mod sph_echo_test;
mod sph_jh_test;
mod sph_groestl_test;
mod sph_keccak_test;
mod sph_skein_test;
mod sph_luffa_test;
mod sph_shavite_test;
mod sph_simd_test;
mod sph_fugue_test;
mod sph_hamsi_test;
mod sph_whirlpool_test;
mod sph_haval_test;
mod sph_panama_test;
mod sph_ripemd_test;
mod sph_radiogatun_test;
mod sph_tiger_test;
mod sph_shabal_test;
mod sph_md2_test;
mod sph_md4_test;
mod sph_md5_test;
